# A workaround for supporting Python in MacOS:
# https://pythonhosted.org/CodeChat/.travis.yml.html

matrix:
  include:
  - os: linux
    python: "2.7"
    env: COVERAGE=false
  - os: linux
    python: "3.4"
    env: COVERAGE=false
  - os: linux
    python: "3.5"
    env: COVERAGE=false
  - os: linux
    python: "3.6"
    env: COVERAGE=true
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=2.7 VENV=venv COVERAGE=false
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.4 VENV=venv COVERAGE=false
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.5 VENV=venv COVERAGE=false
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv COVERAGE=false

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    git clone https://github.com/MacPython/terryfy.git
    # Avoid printing the lines from the script below.
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $VERSION $VENV
  fi

install:
  - python -m pip install -U pip
  - pip install -r requirements.txt
  - pip install coverage
  - python setup.py install

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/test_tools.sh; fi
  - if [[ $COVERAGE == "true" ]]; then python -m coverage run -m pytest ./tests; fi
  - if [[ $COVERAGE == "false" ]]; then python -m pytest ./tests; fi

after_success: |
  if [[ $COVERAGE == "true" ]]; then
    coveralls --rcfile='hcipy/tests/coveragerc'
  fi