jobs:
- job:
  displayName: Linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  
  - bash:
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=$PYTHON_VERSION numpy scipy
    displayName: Set up Anaconda

  - bash: |
      source activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - bash: |
      source activate test-environment
      pytest ./tests
    displayName: Run tests

- job:
  displayName: MacOS
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  
  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=$PYTHON_VERSION numpy scipy
    displayName: Set up Anaconda

  - bash: |
      source activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - bash: |
      source activate test-environment
      pytest ./tests
    displayName: Run tests

- job:
  displayName: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy
    displayName: Set up Anaconda

  - script: |
      call activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - script: |
      call activate myEnvironment
      pytest ./tests
    displayName: Run tests
