jobs:
- job:
  displayName: Linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=$PYTHON_VERSION numpy scipy
    displayName: Set up Anaconda environment

  - bash: |
      source activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - bash: |
      python --version
      python -c "import numpy; print('Numpy', numpy.__version__)"
      python -c "import scipy; print('Scipy', scipy.__version__)"
      python -c "import matplotlib; print('Matplotlib', matplotlib.__version__)"
      python -c "import hcipy; print('HCIPy', hcipy.__version__)"
    displayName: Print package versions

  - bash: |
      source activate test-environment
      python -m pytest ./tests --junitxml=junit/unit-test.xml
    displayName: Run tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/*.xml'
    condition: succeededOrFailed()

- job:
  displayName: MacOS
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=$PYTHON_VERSION numpy scipy
    displayName: Set up Anaconda environment

  - bash: |
      source activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - bash: |
      python --version
      python -c "import numpy; print('Numpy', numpy.__version__)"
      python -c "import scipy; print('Scipy', scipy.__version__)"
      python -c "import matplotlib; print('Matplotlib', matplotlib.__version__)"
      python -c "import hcipy; print('HCIPy', hcipy.__version__)"
    displayName: Print package versions

  - bash: |
      source activate test-environment
      pytest ./tests --junitxml=junit/unit-test.xml
    displayName: Run tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/*.xml'
    condition: succeededOrFailed()

- job:
  displayName: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
      conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy
    displayName: Set up Anaconda environment

  - script: |
      call activate test-environment
      pip install pytest pytest-azurepipelines
      pip install ".[dev]"
    displayName: Install HCIPy

  - bash: |
      python --version
      python -c "import numpy; print('Numpy', numpy.__version__)"
      python -c "import scipy; print('Scipy', scipy.__version__)"
      python -c "import matplotlib; print('Matplotlib', matplotlib.__version__)"
      python -c "import hcipy; print('HCIPy', hcipy.__version__)"
    displayName: Print package versions

  - script: |
      call activate test-environment
      pytest ./tests --junitxml=junit/unit-test.xml
    displayName: Run tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/*.xml'
    condition: succeededOrFailed()